provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  neo4j-register:
    lang: node
    handler: ../neo4j-register
    image: jaigouk/neo4j-register
    environment_file:
      - function_secrets.yml
  neo4j-gql:
    lang: node
    handler: ../neo4j-gql
    image: jaigouk/neo4j-gql
    environment_file:
      - function_secrets.yml
  neo4j-login:
    lang: node
    handler: ../neo4j-login
    image: jaigouk/neo4j-login
    environment_file:
      - function_secrets.yml
  s2-point:
    lang: dockerfile
    handler: ../s2-point
    image: jaigouk/s2-point
